### PR TITLE
Errors handling and user feedback (based on #154)

### LINKED ISSUE #148: Basic error management in monujo is missing
Lokapi will throw exceptions. In most calls to lokapi, no visible action for the end-user is taken to warn that the loading finished in an error, or resulted in a blocked / empty list because of an error. I suggest that we catch the errors and at least display something like "Uho, something went wrong, sorry. Please contact your administrator if this error doesn't go away."
It is nice that usable information is provided for debug in the javascript console also.

### PR DESCRIPTION
**Pull request by seegwen**
Report error to the user with a toast if there is a network error while trying to autologin
Make all empty data lists (credits, accounts, pending accounts, transactions) homogenous and show look-alike messages.
Catch lokapi errors
Make these errors bubble up in the UI as graceful "unavailability" messages.

(closes #148)

### CODE REVIEW

**Comment by seegwen** [comment]
Add a clickable cross indicating to the user that he can close the toast

**Review by stephansainleger — APPROVED** [review]
Technical review OK
Functional review OK

File: src/views/admin/PendingCredits.vue [hunk 1]
```diff
@@ -57,12 +58,20 @@
...
+    },
     mounted() {
       this.updatePendingCreditRequests()
     },
     computed: {
       pendingCreditRequests(): Array<any> {
         return this.$store.state.lokapi.pendingCreditRequests
+      },
+      hasLoadingError(): Array<any> {
+        return this.$store.state.lokapi.pendingCreditRequestsError
```
Comment (stephansainleger) [inline src/views/admin/PendingCredits.vue:74]: useless call on a non-existing variable in the store

**Review by stephansainleger — CHANGES_REQUESTED** [review]

File: src/views/admin/PendingCredits.vue (hunk 1 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue]: Thanks for spotting the error.
Changed.

File: src/store/lokapi.ts [hunk 2]
```diff
@@ -120,7 +128,7 @@ export function lokapiStoreFactory(lokApiService: any) {
         try {
           commit('storeBackends', await lokApiService.getBackends())
         } catch (err:any) {
-          console.error('Error getting currency backends', err)
+          console.error('Error getting currency backends', err.message, "\nDebug: " + JSON.stringify(err))
```
Comment (vaab) [inline src/store/lokapi.ts:137]: The arguments of console.error and console.log are stringified, no need to do it yourself and can be displayed by browser in a much better way by themselves (indeed, it is the reference of the object that is sent, so the exception gets to be dynamically printed and choose how it wants to be displayed. Maybe err.message is not used as you think it is in these exceptions). You are effectively casting the exception towards strings, and I don't understand the call to  `JSON.stringify()` here, I'm obviously missing something you wanted to achieve.

File: src/store/lokapi.ts [hunk 3]
```diff
@@ -63,20 +63,28 @@ export function lokapiStoreFactory(lokApiService: any) {
...
       async fetchAccounts({commit}:any) {
         commit("setAccountsLoading", true)
-        const { virtualAccountTree, allMoneyAccounts } = await lokApiService.buildVirtualAccountTree()
-        commit("setAccounts", { virtualAccountTree, allMoneyAccounts })
+        try {
+          const { virtualAccountTree, allMoneyAccounts } = await lokApiService.buildVirtualAccountTree()
+          commit("setAccounts", { virtualAccountTree, allMoneyAccounts })
+        } catch (e:any) {
+          console.error('Error fetching wallets', e.message, "\nDebug: " + JSON.stringify(e))
+        }
```
Comment (vaab) [inline src/store/lokapi.ts:75]: You are hiding the error to the UI and prevent it to take the choice to display or not message by catching the exception and display something or just ignore it. I don't think this is the way to go.
Inner layer (like the store) should let these exception bubble up to let the choice to the UI of the course of action.
You can of course add some behavior on the go here like removing `setAccountsLoading` to false, just don't forget to throw the err after.

File: src/store/lokapi.ts [hunk 4]
```diff
@@ -63,20 +63,28 @@ export function lokapiStoreFactory(lokApiService: any) {
...
+        try {
+          transactionsGen = lokApiService.getTransactions()
+          let next = await transactionsGen.next()
+          while (!next.done && transactionsIndex < transactionsBatchLength) {
+            transactionsIndex++
+            transactions.push(<any>next.value)
+            next = await transactionsGen.next()
+          }
+        } catch (e:any) {
+          console.error('Error fetching transactions', e.message, "\nDebug: " + JSON.stringify(e))
```
Comment (vaab) [inline src/store/lokapi.ts:92]: Same remark here than previously.
Note that the console.error message isn't adding much as the exception will write its own message if not caught. We can still give the caller the choice of displaying in the console this message or not.

File: src/views/admin/PendingAccounts.vue [hunk 5]
```diff
@@ -87,7 +87,11 @@
     },
     async updatePendingAccount(){
       this.isLoading = true
-      await this.$store.dispatch('fetchPendingUserAccounts')
+      try {
+        await this.$store.dispatch('fetchPendingUserAccounts')
+      } catch (e:any) {
+        console.error('Failed to fetch pending accounts', e.message + "\nDebug: " + JSON.stringify(e))
+      }
```
Comment (vaab) [inline src/views/admin/PendingAccounts.vue:98]: I was expecting a message for the user in lieu of the "no pending accounts". Here the console.error doesn't bring a lot of difference than not catching the exception, does it ?

File: src/views/admin/PendingCredits.vue [hunk 6]
```diff
@@ -87,6 +87,13 @@
           showConfirmButton: false,
           timer: 3000
         })
+      },
+      async updatePendingCreditRequests() {
+        try {
+          await this.$store.dispatch('fetchPendingCreditRequests')
+        } catch (e:any) {
+          console.error('Failed to fetch pending credit requests', e.message + "\nDebug: " + JSON.stringify(e))
+        }
```
Comment (vaab) [inline src/views/admin/PendingCredits.vue:104]: same remark, a message visible to the end-user was expected.

File: src/components/leftCol/YourAccs.vue [hunk 7]
```diff
@@ -71,6 +72,9 @@
       isLoadingAccounts(): boolean {
         return this.$store.state.lokapi.accountsLoading
       },
+      hasAccountsLoadingError(): boolean {
+        return this.$store.state.lokapi.accountsLoadingError
+      },
```
Comment (vaab) [inline src/components/leftCol/YourAccs.vue:77]: I don't see why this would need to be put in the store as it concerns only this UI component. You are effectively adding variable in the store that are for only one component. You could have done a simple try/catch here and have the logic of this component kept close to the component.

If you had plans to use this in other components, this would have made sense to me.

No modification was required in the store with a lot of intelligence of individual components that makes it big and cluttered.

I noticed you've done what I suggest for `PendingAccounts` and `PendingCredits`.

File: src/components/rightCol/ThisWeek.vue [hunk 8]
```diff
@@ -39,7 +40,10 @@
       },
       isLoadingTransactions(): boolean {
         return this.$store.state.lokapi.transactionsLoading
-      }
+      },
+      hasTransactionsLoadingError(): boolean {
+        return this.$store.state.lokapi.transactionsLoadingError
+      },
```
Comment (vaab) [inline src/components/rightCol/ThisWeek.vue:46]: Same remark

File: src/views/admin/PendingAccounts.vue [hunk 9]
```diff
@@ -9,9 +9,10 @@
           <loading v-model:active="isLoading"
                :can-cancel="false"
                :is-full-page= "false"/>
+          <p class="notification is-danger is-light" v-if="hasLoadingError">Liste des comptes en attente de validation indisponible</p>
```
Comment (vaab) [inline src/views/admin/PendingAccounts.vue:12]: For the formulation, we need to be more explicit and tell that an unexpected error happened. Maybe even apologies ? And give an action. Try to reload or contact your administrator.

File: src/views/admin/PendingCredits.vue [hunk 10]
```diff
@@ -7,9 +7,10 @@
             class="accounts card custom-card custom-card-padding"
           >
             <h2 class="custom-card-title">Opérations de crédit en attente de validation</h2>
+            <p class="notification is-danger is-light" v-if="hasLoadingError">Liste des demandes de crédit indisponible</p>
```
Comment (vaab) [inline src/views/admin/PendingCredits.vue:10]: same comment about being explicit and give an action to move forward

File: src/App.vue [hunk 11]
```diff
@@ -15,7 +15,16 @@
           console.log("Trying to Autolog")
           await this.$store.dispatch("initAutoLogin")
         } catch(e) {
-          console.error("Error while trying to autolog", e)
+          if (e.name !== 'TokenRequired') {
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:18]: Ok. Thanks for the snippet.

[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:18]: Cleaner and probably the recommended way as you stated above. Will do.

File: src/App.vue [hunk 12]
```diff
@@ -15,7 +15,16 @@
...
+            console.error("Error while trying to autolog", e.message + "\nDebug: " + JSON.stringify(e))
+            this.$toast.error(
+              "<button class=\"delete\"></button>" +
+              "Woops !<br>" +
+              "Une erreur est survenue en essayant de vous connecter automatiquement.<br>" +
+              "Si le problème persiste, veuillez contacter votre administrateur.",
+              { position: "bottom", duration: false }
+            )
+          }
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:27]: All this login mechanism is really not how I'm used to do things. I bear with you on this one.

File: src/views/admin/PendingAccounts.vue [hunk 13]
```diff
@@ -3,17 +3,17 @@
...
-          <div
-            v-if="!isLoading" class="accounts card custom-card custom-card-padding"
-          >
-         <div v-if="pendingUserAccounts.length === 0">Aucun compte en attente de validation</div>
+          <div class="accounts card custom-card custom-card-padding">
          
-        <div v-else>
-         <h2 class="custom-card-title">Comptes en attente de validation</h2>
-          <table   class="table is-striped is-fullwidth">
+          <h2 class="custom-card-title">Comptes en attente de validation</h2>
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:8]: To me its kinda awkward to either have a title, or not depending of the contents displayed. There should be one, always, or never.

It's the same thing as having a loading-indicator make a title hide, and then displayed. The user should know about what is actually loading underneath.

File: src/store/lokapi.ts (hunk 2 above)
Comment (seegwen) [reply src/store/lokapi.ts:137]: I don't like my js console cluttered with stack traces, that's why I chose to make it more tidy. Have the reason of the error on the first line, then additional information below, as a string which can be copy-pasted by anyone, and give to someone competent to analyze. Maybe that's useless.

So if I understand you, you would just keep the `console.error('Error getting currency backends', err)` ?

File: src/store/lokapi.ts (hunk 3 above)
Comment (seegwen) [reply src/store/lokapi.ts:75]: ? I think there is a misunderstanding here:
One commit is in charge of catching the errors and make the accounts loading-indicator at least stop. Which is an improvement over the previous state of things which rendered the UI loading indefinitely.
The next and last commit of this PR is responsible of adding feedback to the user, which again is an improvement over the previous commit. I could have done it sqashed. I made this on purpose. First fix something broken. Then add some functionality.

Then again, as some replies to your comments below state, you are missing that the `fetchAccounts` action is not called from a component but from the store itself, so this is the place where the exception should be catched and action taken. As my replies below also state, I'd really be interested to know how you would do it, as I may be missing something.

File: src/store/lokapi.ts (hunk 4 above)
Comment (seegwen) [reply src/store/lokapi.ts:92]: Hmmm. `resetTransactions` action is also called from the store. So the caller is the store. The store decided to write the message to the js console. As stated below, it's a tradeof, not ideal I agree, but unless we tie all the action calls in components I think that's the way to do it.

File: src/views/admin/PendingAccounts.vue (hunk 5 above)
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:98]: This commit fixes the error by catching it and reporting it in the console. The next commit adds functionality by providing feedback to the user.

File: src/views/admin/PendingCredits.vue (hunk 6 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue:104]: It's handled by the next commit, same as above.

File: src/components/leftCol/YourAccs.vue (hunk 7 above)
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:77]: This is how @SeddikKadi did it, and I second his choice, because as the accounts list is created from the store with the `fetchAccounts` method , you cannot catch the error at the component level. It's not ideal but it's a tradeof, it's clean, and it works. If all the actions where to be tied from the components then what you suggest would be doable. It's not the case, and that's why it's done in PendingCredits and PendingAccounts on the component level, because this specific action is catchable from there.
But I'd be glad to know how you would do it, I may be missing something here.

File: src/components/rightCol/ThisWeek.vue (hunk 8 above)
Comment (seegwen) [reply src/components/rightCol/ThisWeek.vue:46]: Yes, same answer as above 😄

File: src/views/admin/PendingAccounts.vue (hunk 9 above)
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:12]: Ok, I took your suggestion from the RC to the word I thought that's what you thought about in the first place.
I will make a more explicit explanation of the error.

File: src/views/admin/PendingCredits.vue (hunk 10 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue:10]: Yes, will do.

File: src/App.vue (hunk 11 above)
[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:18]: But again I think I don't understant what you mean. Sorry. I'm trying my best.

File: src/App.vue (hunk 12 above)
[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:27]: Fixed.

File: src/views/admin/PendingAccounts.vue (hunk 13 above)
[the remark this answers is not in the document]
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:8]: All this is important since it's part of the user experience. But it is subjective and YMMV.
In the end I don't have a strong opinion. Just did as I felt at the moment.

Changed.

File: src/views/admin/PendingAccounts.vue (hunk 9 above)
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:12]: Changed.

File: src/views/admin/PendingCredits.vue (hunk 10 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue:10]: Changed.

File: src/store/lokapi.ts (hunk 2 above)
Comment (seegwen) [reply src/store/lokapi.ts:137]: ?
Changed.

File: src/store/lokapi.ts (hunk 3 above)
Comment (seegwen) [reply src/store/lokapi.ts:75]: Squashed commits. Changed.

File: src/views/admin/PendingAccounts.vue (hunk 5 above)
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue:98]: Squashed commits. Changed.

File: src/views/admin/PendingCredits.vue (hunk 6 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue:104]: Squashed commits. Changed.

File: src/components/leftCol/YourAccs.vue (hunk 7 above)
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:77]: This one really is tricky. I'd be glad to receive your suggestion.

File: src/components/rightCol/ThisWeek.vue (hunk 8 above)
Comment (seegwen) [reply src/components/rightCol/ThisWeek.vue:46]: Same here. If you have a suggestion on how to do it, please advise.

**Comment by seegwen** [comment]
@vaab  Thanks for your feedback. I acted upon it.

File: src/assets/main.scss [hunk 14]
```diff
@@ -731,4 +731,14 @@ input {
...
+}
+
+.c-toast {
+  position: relative;
+
+  .delete {
+    position: absolute;
+    top: .4rem;
+    right: .4rem;
+  }
```
Comment (vaab) [inline src/assets/main.scss:743]: is this still necessary if you don't have any toaster introduced in this commit ? Same for the commit message, that seems to need to be updated.

File: src/App.vue (hunk 11 above)
[the remark this answers is not in the document]
Comment (vaab) [reply src/App.vue]: I'm probably often not as clear as I would like to. Don't hesitate to ask specific questions so we can move forward. What are you not understanding ? The comment in the code ? my remark ? the internals I'm referring to ? Looking forward to build a common understanding of the current situation to be able to leverage your own ideas an initiatives to improve further.

File: src/views/admin/PendingAccounts.vue (hunk 13 above)
[the remark this answers is not in the document]
Comment (vaab) [reply src/views/admin/PendingAccounts.vue]: You have your point about having a title while loading. My point was only that the title is a little awkward once we know the list is empty (after the loading). No strong feelings about this, and I don't think it is this important either way.

File: src/assets/main.scss (hunk 14 above)
Comment (seegwen) [reply src/assets/main.scss]: Thanks for the heads-up.

Changed.

File: src/views/admin/PendingAccounts.vue (hunk 13 above)
[the remark this answers is not in the document]
Comment (seegwen) [reply src/views/admin/PendingAccounts.vue]: Me neigher so I did as you suggested.

File: src/views/admin/PendingCredits.vue [hunk 15]
```diff
@@ -88,6 +97,15 @@
...
         })
+      },
+      async updatePendingCreditRequests() {
+        try {
+          await this.$store.dispatch('fetchPendingCreditRequests')
+          this.hasLoadingError = false
+        } catch (e:any) {
+          console.error('Failed to fetch pending credit requests', e)
+          this.hasLoadingError = true
+        }
```
Comment (vaab) [inline src/views/admin/PendingCredits.vue:108]: There are no loading symbol displayed nor managed, is that intended ?

**Review by vaab — CHANGES_REQUESTED** [review]
Thanks, it seems good to me once the remaining points are cleared.

File: src/App.vue [hunk 16]
```diff
@@ -15,7 +16,16 @@
...
+            // TokenRequired is cast by lokapi as one of 2 mecanism to
+            // react upon failure of auto-login. As we are already using
+            // the ``requestLogin`` callback, and that this callback issues
+            // a ``router.push("/")`` that won't do anything when already
+            // on this URL, this code will be run and this exception will
+            // be thrown and catched here. Notice that if the login page
+            // was on the URL "/login", that would not be necessary.
+            return
+          }
         }
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/App.vue:29]: Changed.

File: src/components/leftCol/YourAccs.vue [hunk 17]
```diff
@@ -3,33 +3,35 @@
...
+        @click="refreshBalanceAndTransactions"
+        title="Rafraîchir le solde et les transactions"
+        class="button is-default is-pulled-right is-rounded refresh"
       >
-        <template v-slot:name>{{ account.name }}</template>
-      </Acc>
+        <span>Rafraîchir</span>
+        <span class="icon is-small">
+          <i class="fas fa-sync"></i>
+        </span>
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:19]: Weird, on my end it is properly displayed upon the error message. That's what the extra line of css of this commit is introduced for.

File: src/components/leftCol/YourAccs.vue [hunk 18]
```diff
@@ -18,7 +18,11 @@
           <i class="fas fa-sync"></i>
         </span>
       </a>
-      <p class="notification is-default" v-if="totalAccountsLoaded === 0">Vous n'avez pas encore de compte</p>
+      <div class="notification is-danger is-light" v-if="hasAccountsLoadingError">
+        <p class="mb-4">Une erreur inattendue est survenue pendant le chargement des portefeuils. Veuillez nous excuser pour le désagrément.</p>
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:22]: Laughs. Thanks. Changed.

File: src/components/rightCol/ThisWeek.vue [hunk 19]
```diff
@@ -3,7 +3,11 @@
             :can-cancel="false"
             :is-full-page="false"/>
   <div v-if="!isLoadingTransactions">
-    <p v-if="getTrs?.length === 0" class="notification is-default"> Aucune opération dans votre historique</p>
+    <div class="notification is-danger is-light" v-if="hasTransactionsLoadingError">
+      <p class="mb-4">Une erreur inattendue est survenue pendant le chargement des opérations. Veuillez nous excuser pour le désagrément.</p>
```
[the remark this answers is not in the document]
Comment (seegwen) [reply src/components/rightCol/ThisWeek.vue:7]: "Opérations" or "transactions" feels pretty much the same to me.
On my bank website, these are called operations and not transactions. And it seems to me that a credit operation is an operation, not a transaction involving multiple parties.
But I agree the message could be more specific.
I did change it to "chargement des dernières opérations de votre compte".

If you insist that I put "transactions", I will also change the title of the box and the title of the modal.

File: src/views/admin/PendingCredits.vue (hunk 15 above)
Comment (seegwen) [reply src/views/admin/PendingCredits.vue:108]: This PR does not introduce loading indicators, which was work done by seddik. He did not implement it.
Please see PR #156

File: src/components/leftCol/YourAccs.vue (hunk 17 above)
[the remark this answers is not in the document]
Comment (vaab) [reply src/components/leftCol/YourAccs.vue:19]: Maybe, I had the button re-appear on top. But now it is also on top of the modals (Pay modal for instance). Which is not good ;-).

[the remark this answers is not in the document]
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:19]: Aaah yes. Haven't checked that one.

File: src/components/rightCol/ThisWeek.vue (hunk 19 above)
[the remark this answers is not in the document]
Comment (vaab) [reply src/components/rightCol/ThisWeek.vue]: no that's perfect for me.

File: src/views/admin/PendingCredits.vue (hunk 15 above)
Comment (vaab) [reply src/views/admin/PendingCredits.vue:108]: ok, thanks for the heads up.

**Comment by vaab** [comment]
It seems that errors on `searchRecipients()` calls (in `SendAskMoney.vue` were not handled. Is that intended ? This one seems important.

File: src/components/leftCol/YourAccs.vue (hunk 17 above)
[the remark this answers is not in the document]
Comment (seegwen) [reply src/components/leftCol/YourAccs.vue:19]: Thanks for being that vigilant. I was checking with the transactions modal only... the footer ones behave differently as you reported. It should really be fixed now.

**Comment by seegwen** [comment]
> It seems that exception thrown by lokapi on the call to `.searchRecipients()` (in `SendAskMoney.vue`) were not handled. Is that intended ? This one seems important.

They were not indeed. They are now. Thanks.

File: src/components/leftCol/YourAccs.vue (hunk 17 above)
[the remark this answers is not in the document]
Comment (vaab) [reply src/components/leftCol/YourAccs.vue:19]: Looks good to me !

**Review by vaab — APPROVED** [review]
