### PR TITLE
fix: ui: fix the credit modal flow (Closes #8)

### LINKED ISSUE #8: "Credit" Modal : "Suivant" button creates a new quotation each times and nothing happens
I expected button "Suivant" to go back, or to tell us what quotations are waiting to be paid.

Whatever is chosen, I didn't expect it to create as many quotation that I clicked on "Suivant". This might be a problem.

Could we at least:
- NOT create an additional quotation when clicking on "Suivant"  when we already have an url generated ?
- Maybe remove the button Suivant and change it to Done, or some text to explain that the account will only be credited
  when created order will be paid thanks to the given link ?

The suggestion of removing "Suivant", and having a "Done" button to close the modal avoids the user to click on the cross to close the modal, even if everything went as expected.

### PR DESCRIPTION
**Pull request by seegwen**
chg: ui: hide the credit form upon clicking on "Done" ("terminer")
button

Will show a message explaining the next step in the process is to click
on a link and finalize transaction in Odoo, show a button letting the
user to go through this next step.

A click on the button closes the modal and opens a new window
at the address of the order that was just created.

### CODE REVIEW

File: src/components/sendAskMoney/SendAskMoney.vue [hunk 1]
```diff
@@ -889,13 +889,11 @@
...
-          <div class="is-flex is-flex-direction-column custom-montant-input">
+          <div v-if="myHyperLink.length === 0" class="is-flex is-flex-direction-column custom-montant-input">
             <h2 class="frame3-sub-title mt-3 mb-3">
               Montant à créditer
             </h2>
-            <input v-model="amountForCredit" type="number" min="0" class="p-2" />
-            <h2 v-if="myHyperLink.length > 1" class="mt-6 mb-2 frame3-sub-title">Vous n'avez pas été redirigé ?</h2>
-            <a class="mt-6" target="_blank" :href="urlForHyperlink">{{urlForHyperlink}}</a>
+            <input v-model="amountForCredit" type="number" min="0" class="p-2 mb-3" />
             <!-- <h2 class="mt-6 mb-6 frame3-sub-title">Mode de paiement</h2> -->
```
Comment (stephansainleger) [inline src/components/sendAskMoney/SendAskMoney.vue:897]: you can remove this commented lines, linked to an old design not relevant today

**Review by stephansainleger — APPROVED** [review]
